apiVersion: v1
kind: Service
metadata:
  name: jmeter-reporter-svc
  labels:
    jmeter_mode: reporter
spec:
  ports:
    - port: 8686
      targetPort: 8686
  selector:
    jmeter_mode: reporter
  type: NodePort

---
apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: jmeter-reporter
  name: jmeter-reporter-lb
spec:
  ports:
  - name: 8686-8686
    port: 8686
    protocol: TCP
    targetPort: 8686
  selector:
    jmeter_mode: reporter
  type: LoadBalancer
status:
  loadBalancer: {}