apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: jmeter-reporter-svc
  name: jmeter-reporter-svc
spec:
  ports:
  - name: 8686-8686
    port: 8686
    protocol: TCP
    targetPort: 8686
  selector:
    jmeter_mode: reporter
  type: LoadBalancer
status:
  loadBalancer: {}