apiVersion: v1
kind: Service
metadata:
  name: jmeter-grafana
  labels:
    app: jmeter-grafana
spec:
  ports:
    - port: 3000
      targetPort: 3000
  selector:
    app: jmeter-grafana
  type: NodePort

---
apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: jmeter-grafana
  name: jmeter-grafana-lb
spec:
  ports:
  - name: 3000-3000
    port: 3000
    protocol: TCP
    targetPort: 3000
  selector:
    app: jmeter-grafana
  type: LoadBalancer
status:
  loadBalancer: {}
