apiVersion: apps/v1
kind: Deployment
metadata:
  name: jmeter-reporter
  labels:
    jmeter_mode: reporter
spec:
  replicas: 1
  selector:
    matchLabels:
      jmeter_mode: reporter
  template:
    metadata:
      labels:
        jmeter_mode: reporter
    spec:
      containers:
      - name: jmreporter
        image: kubernautslabs/jmeter-reporter:latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8686
      tolerations:
        - key: "type"
          operator: "Equal"
          value: "jmeter"
          effect: NoExecute
