apiVersion: v1
kind: DeploymentConfig
metadata:
  name: jmeter-influxdb
  labels:
    app: jmeter-influxdb
spec:
  replicas: "1"
  selector:
    matchLabels:
      app: jmeter-influxdb
  template:
    metadata:
      labels:
        app: jmeter-influxdb
    spec:
      containers:
        - image: influxdb
          name: influxdb
          volumeMounts:
          - name: config-volume
            mountPath: /etc/influxdb
          ports:
            - containerPort: 8083
              name: influx
            - containerPort: 8086
              name: api
            - containerPort: 2003
              name: graphite
      volumes:
      - name: config-volume
        configMap:
         name: influxdb-config